deploy:
  version: 2020111

namespace: demo

deployment:
  redis:
    replicaCount: 1
    port: 6379
  flask:
    replicaCount: 1
    image:
      repository: davidh83110/flask-test
      tag: latest
    health_path: /health
  
secrets:
  username:
    key: USERNAME
    value: bob
  password:
    key: PASSWORD
    value: "1234567890"
  thebigsecret:
    key: THEBIGSECRET
    value: "The is a big secret"

ingress:
  allowIP: "61.220.65.15/32"



