language: python

sudo: required
dist: xenial
services: docker
#branches:
#  only:
#    - master

env:
  global:
    - DEPLOY_VERSION=$TRAVIS_COMMIT

install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - helm version
  - pip install --upgrade awscli
  - aws --version
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
  - kubectl version --client
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
  - chmod +x ./aws-iam-authenticator && mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin && echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - aws-iam-authenticator help

before_script:
  - cd terraform/eks && make init && make plan && make apply
  - aws eks --region eu-west-2 update-kubeconfig --name demo-cluster

script:
  - docker build -t flask ./app
#  - docker tag flask xxxx:$TRAVIS_COMMIT
#  - $(aws ecr get-login --no-email)
#  - docker push xxxx:$TRAVIS_COMMIT
#  - helm upgrade app ./chart --dry-run --debug --set xxxxx
#  - helm upgrade app ./chart

after_script:
  - echo "Deployed."
